/**
 * Social Message API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Http, Headers, RequestOptionsArgs, Response, URLSearchParams} from '@angular/http';
import {Injectable, Optional} from '@angular/core';
import {Observable} from 'rxjs/Observable';
import * as models from '../model/models';
import 'rxjs/Rx';

/* tslint:disable:no-unused-variable member-ordering */

'use strict';

@Injectable()
export class FeedApi {
    protected basePath = 'http://localhost:10010/';
    public defaultHeaders : Headers = new Headers();

    constructor(protected http: Http, @Optional() basePath: string) {
        if (basePath) {
            this.basePath = basePath;
        }
    }

    /**
     * 
     * Create a feed
     * @param id 
     * @param idtoken 
     * @param accessToken 
     */
    public authorizeToScrap (id: string, idtoken: string, accessToken: string, extraHttpRequestParams?: any ) : Observable<models.GeneralResponse> {
        const path = this.basePath + '/feed/{id}/authorizeToScrap'
            .replace('{' + 'id' + '}', String(id));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling authorizeToScrap.');
        }
        // verify required parameter 'idtoken' is not null or undefined
        if (idtoken === null || idtoken === undefined) {
            throw new Error('Required parameter idtoken was null or undefined when calling authorizeToScrap.');
        }
        // verify required parameter 'accessToken' is not null or undefined
        if (accessToken === null || accessToken === undefined) {
            throw new Error('Required parameter accessToken was null or undefined when calling authorizeToScrap.');
        }
            headerParams.set('idtoken', String(idtoken));

            headerParams.set('access_token', String(accessToken));

        let requestOptions: RequestOptionsArgs = {
            method: 'POST',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 
     * Create a feed
     * @param idtoken 
     * @param feed 
     * @param facebookaccesstoken 
     */
    public create (idtoken: string, feed: models.Feed, facebookaccesstoken?: string, extraHttpRequestParams?: any ) : Observable<models.Feed> {
        const path = this.basePath + '/feeds';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'idtoken' is not null or undefined
        if (idtoken === null || idtoken === undefined) {
            throw new Error('Required parameter idtoken was null or undefined when calling create.');
        }
        // verify required parameter 'feed' is not null or undefined
        if (feed === null || feed === undefined) {
            throw new Error('Required parameter feed was null or undefined when calling create.');
        }
            headerParams.set('idtoken', String(idtoken));

            headerParams.set('facebookaccesstoken', String(facebookaccesstoken));

        let requestOptions: RequestOptionsArgs = {
            method: 'POST',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(feed);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 
     * Deletes the feed for the provided id
     * @param idToken 
     * @param id Id of the feed to be deleted
     */
    public deleteById (idToken: string, id: string, extraHttpRequestParams?: any ) : Observable<models.GeneralResponse> {
        const path = this.basePath + '/feed/{id}'
            .replace('{' + 'id' + '}', String(id));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'idToken' is not null or undefined
        if (idToken === null || idToken === undefined) {
            throw new Error('Required parameter idToken was null or undefined when calling deleteById.');
        }
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deleteById.');
        }
            headerParams.set('idToken', String(idToken));

        let requestOptions: RequestOptionsArgs = {
            method: 'DELETE',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 
     * Returns list of feeds to caller
     * @param idToken 
     */
    public list (idToken: string, extraHttpRequestParams?: any ) : Observable<Array<models.Feed>> {
        const path = this.basePath + '/feeds';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'idToken' is not null or undefined
        if (idToken === null || idToken === undefined) {
            throw new Error('Required parameter idToken was null or undefined when calling list.');
        }
            headerParams.set('idToken', String(idToken));

        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 
     * Returns the feed for the supplied id to the caller
     * @param idToken 
     * @param id Id of the feed to be returned
     */
    public readById (idToken: string, id: string, extraHttpRequestParams?: any ) : Observable<Array<models.Feed>> {
        const path = this.basePath + '/feed/{id}'
            .replace('{' + 'id' + '}', String(id));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'idToken' is not null or undefined
        if (idToken === null || idToken === undefined) {
            throw new Error('Required parameter idToken was null or undefined when calling readById.');
        }
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling readById.');
        }
            headerParams.set('idToken', String(idToken));

        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 
     * Create a feed
     * @param id 
     * @param idtoken 
     * @param contentText 
     */
    public scrapNewPostsFromSource (id: string, idtoken: string, contentText?: models.GeneralResponse, extraHttpRequestParams?: any ) : Observable<models.GeneralResponse> {
        const path = this.basePath + '/feed/{id}/scrapNewPostsFromSource'
            .replace('{' + 'id' + '}', String(id));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling scrapNewPostsFromSource.');
        }
        // verify required parameter 'idtoken' is not null or undefined
        if (idtoken === null || idtoken === undefined) {
            throw new Error('Required parameter idtoken was null or undefined when calling scrapNewPostsFromSource.');
        }
            headerParams.set('idtoken', String(idtoken));

        let requestOptions: RequestOptionsArgs = {
            method: 'POST',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(contentText);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 
     * Update an existing feed
     * @param idToken 
     * @param id 
     * @param feed 
     * @param facebookaccesstoken 
     */
    public updateById (idToken: string, id: string, feed: models.Feed, facebookaccesstoken?: string, extraHttpRequestParams?: any ) : Observable<models.PutResponse> {
        const path = this.basePath + '/feed/{id}'
            .replace('{' + 'id' + '}', String(id));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'idToken' is not null or undefined
        if (idToken === null || idToken === undefined) {
            throw new Error('Required parameter idToken was null or undefined when calling updateById.');
        }
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling updateById.');
        }
        // verify required parameter 'feed' is not null or undefined
        if (feed === null || feed === undefined) {
            throw new Error('Required parameter feed was null or undefined when calling updateById.');
        }
            headerParams.set('facebookaccesstoken', String(facebookaccesstoken));

            headerParams.set('idToken', String(idToken));

        let requestOptions: RequestOptionsArgs = {
            method: 'PUT',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(feed);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

}
